#@package _global_
trainer_name: ViFiCLIP
vision_model: VisionTransformer
vision_block: ResidualAttentionBlock
text_block: ResidualAttentionBlock
model_arch: ViT-B/16
patch_size: 16
freeze: null
lr_10x: false

# vision side
n_ctx_vision: 0
prompt_depth_vision: 0

# text side
prompt_model: false
ctx_init: 'a photo of a'
n_ctx_text: 0
prompt_depth_text: 1
context_length: 30
zs_eval: false