# zero-shot setting
defaults:
  - aug: default_aug  # augmentation
  - common: default   # common fields
  - data: zero_shot_k400  # data protocol
  - hydra_configs: default_hydra
  - logging: wandb    # logging
  - optimizer: adamw  # optimizer, scheduler
  - trainer: tc_clip  # model
  - _self_

protocol: zero_shot
resume: null  # checkpoint path
output: ???   # output path
eval: null    # eval=test/val for eval-only mode
use_wandb: true

# Run parameters
epochs: 10  # total epochs
warmup_epochs: 5
lr: 8e-06
lr_min: 8e-08
total_batch_size: 256
batch_size: 4  # batch per gpu
accumulation_steps: 16  # 4gpu case
test_batch_size: 8
num_workers: 8
pin_memory: true
worker_init_fn: true
wise_ft: 0.0  # weight ensemble ratio

# view
input_size: 224
num_frames: 16
num_clip: 1   # single view during training
num_crop: 1
multi_view_inference: true  # multi view during final testing

# Run tools
seed: 1024
distributed: true
use_cudnn: true
opt_level: O1
auto_resume: false
save_freq: 1
save_intermediate: false
print_freq: 50
final_test: true  # final testing with the best checkpoint after training
early_stop: false # early stopping during training

# others
selected_option: ${hydra:runtime.choices} # selected defaults
overriden_values: ${hydra:overrides}      # overrides with cli arguments